spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  data:
    mongodb:
      uri: mongodb+srv://app:${db.pass}@${db.host}?retryWrites=true&w=majority
      database: ${db.name}
server:
  port: 8082